= Java annotation training
:toc:
:toclevels: 3
:toc-placement: preamble
:lb: pass:[<br> +]
:imagesdir: ./images

By Thomas SCHWENDER (Softeam StarTech Java)

== Overview

== Inheritance

There is *NO* inheritance for annotations, except for classes, using the `@Inherited` meta-annotation.

== Differences between `getAnnotations` and `getDeclaredAnnotations` for `Class`, `Method` and `Field`

The "hack" is that there is *NO difference for those methods for `Method` and `Field`*.

This can be found by looking at the source code, for those 2 classes, `getAnnotations` is inherited from `java.lang.reflect.AccessibleObject`, with the following code:

[source,java]
.java.lang.reflect.AccessibleObject
----
/**
 * @since 1.5
 */
public Annotation[] getAnnotations() {
    return getDeclaredAnnotations();
}
----

But, for `class`, `getAnnotations` is overriden.
In this case, as explained in the Javadoc, you have:

* `getAnnotations`: Returns annotations that are present on this element. If there are no annotations present on this element, the return value is an array of length 0.
* `getDeclaredAnnotations`: Returns this element's annotation for the specified type if such an annotation is directly present, else null. This method ignores inherited annotations. (Returns null if no annotations are directly present on this element.)

To illustrate those differences, have a look at the AnnotationInheritance in my GitHub repo.

== Good to know

* not (easily) possible to get the name of a parameter through an annotation (CHECK if this have to be here or in the reflection training)

== Resources

* http://www.mkyong.com/java/java-custom-annotations-example/
* https://docs.oracle.com/javase/tutorial/java/annotations/basics.html
* http://tutorials.jenkov.com/java/annotations.html#creating-your-own-annotations
* https://docs.oracle.com/javase/8/docs/api/index.html
* http://stackoverflow.com/questions/18512304/difference-between-fieldgetannotations-and-fieldgetdeclaredannotations

