= Java annotation training
:toc:
:toclevels: 3
:toc-placement: preamble
:lb: pass:[<br> +]
:imagesdir: ./images
:icons: font
:source-highlighter: highlightjs

By Thomas SCHWENDER (Softeam StarTech Java)

== Overview

Java annotations were introduced in Java 5.

They are used to provide *metadata* on your Java code. +
As a consequence, they have *no direct effect on the operation of the code they annotate*.

They are generally used for the following purposes:

* *Information for the compiler*: Annotations can be used by the compiler to detect errors or suppress warnings.
* *Compile-time and deployment-time (meaning build-time) processing*: Software tools (like Maven) can process annotation information to generate code, XML files, and so forth.
* *Runtime processing*: Some annotations are available to be examined at runtime, usually through *Java Reflection*.

== Annotation basics

* Shortest form, with no element: 
+
[source,java]
----
@Entity
----
+
The `@` character indicates to the compiler that it is an annotation, after that comes the annotation name.
* With elements:
+
[source,java]
----
@Entity(tableName = "vehicles", primaryKey = "id")
----
+
`tableName` and `primaryKey` are the names of the 2 elements, whose values are respectively set to `vehicules` and `id`.

* titi


== Inheritance

There is *NO* inheritance for annotations, except for classes, using the `@Inherited` meta-annotation.

== Differences between `getAnnotations` and `getDeclaredAnnotations` for `Class`, `Method` and `Field`

The "hack" is that there is *NO difference for those methods for `Method` and `Field`*.

This can be found by looking at the source code, for those 2 classes, `getAnnotations` is inherited from `java.lang.reflect.AccessibleObject`, with the following code:

[source,java]
.java.lang.reflect.AccessibleObject
----
/**
 * @since 1.5
 */
public Annotation[] getAnnotations() {
    return getDeclaredAnnotations();
}
----

But, for `class`, `getAnnotations` is overriden.
In this case, as explained in the Javadoc, you have:

* `getAnnotations`: Returns annotations that are present on this element. If there are no annotations present on this element, the return value is an array of length 0.
* `getDeclaredAnnotations`: Returns this element's annotation for the specified type if such an annotation is directly present, else null. This method ignores inherited annotations. (Returns null if no annotations are directly present on this element.)

To illustrate those differences, have a look at the AnnotationInheritance in my GitHub repo.

== Good to know

* not (easily) possible to get the name of a parameter through an annotation (CHECK if this have to be here or in the reflection training)

== Going deeper: Java annotations preprocessor

== Resources

* http://www.mkyong.com/java/java-custom-annotations-example/
* https://docs.oracle.com/javase/tutorial/java/annotations/basics.html
* http://tutorials.jenkov.com/java/annotations.html#creating-your-own-annotations
* https://docs.oracle.com/javase/8/docs/api/index.html
* http://stackoverflow.com/questions/18512304/difference-between-fieldgetannotations-and-fieldgetdeclaredannotations

